plugin-core/src/main/java/org/jvnet/jaxb2/maven2/RawXJC2Mojo.java

Summary of changes:
- Once "not unknown" -> "unknown".
- Once "URI" -> "URIs".
- Twice "ealiest" -> "earliest".
- Thrice "setup" -> "set up".

Fix a double negation and some typos in the log messages

---

pom.xml

When trying to build the plugin with Java 8, I got an error similar to the one on [this Chinese site](http://www.blogjava.net/andyj2ee/archive/2014/12/17/421502.html), except with an `ArrayIndexOutOfBoundsException` at index 8449 rather than 48188. Upgrading the `maven-plugin-plugin` resolves the issue. (I went with version [3.4](http://jira.codehaus.org/browse/MPLUGIN/fixforversion/20381), but [3.3](http://jira.codehaus.org/browse/MPLUGIN/fixforversion/18959) would work as well. Did not pinpoint which exact ticket fixed the issue on their side.)

Fix JDK 8 build support

---

plugin-2.0/src/main/java/org/jvnet/mjiip/v_2_0/OptionsFactory.java
plugin-2.1/src/main/java/org/jvnet/mjiip/v_2_1/OptionsFactory.java
plugin-2.2/src/main/java/org/jvnet/mjiip/v_2_2/OptionsFactory.java
plugin-core/src/main/java/org/jvnet/jaxb2/maven2/AbstractXJC2Mojo.java
plugin-core/src/main/java/org/jvnet/jaxb2/maven2/OptionsConfiguration.java
plugin-core/src/main/java/org/jvnet/jaxb2/maven2/RawXJC2Mojo.java
plugin/src/main/java/org/jvnet/mjiip/v_2/OptionsFactory.java

Useful for recovering XSD dependencies (in XSD parsing) behind a proxy.
Code extracted from justinsb/jaxb2-maven-plugin (jaxb2 plugin previously in codehaus).

Proxy configuration in maven (settings) used with xjc execution

---

.gitignore
plugin-core/src/main/java/org/jvnet/jaxb2/maven2/AbstractXJC2Mojo.java
plugin-core/src/main/java/org/jvnet/jaxb2/maven2/RawXJC2Mojo.java

This pr adds the following configuration parameters for custom proxy configuration:
* `proxyHost`
* `proxyPort`
* `proxyUsername`
* `proxyPassword`
This solution was selected, because we do want to configure a global HTTP proxy per build.

allow custom proxy configuration

---

plugin-core/src/main/java/org/jvnet/jaxb2/maven2/RawXJC2Mojo.java

To prevent console log from bloating in a project with large quantity of files: Up-to-date check for source resources and target resources logger has been changed to [debug level](https://maven.apache.org/general.html#How_to_produce_execution_debug_output_or_error_messages).

Issue #31. Limit Up-to-date and target resource logging to debug mode

---

plugin-core/src/main/java/org/jvnet/jaxb2/maven2/RawXJC2Mojo.java

This is a proposed fix to issue #130 : only consider jar dependencies when searching for episodes.

Only consider jar dependencies when useDependenciesAsEpisodes is enabled

---

plugin-core/src/main/java/org/jvnet/jaxb2/maven2/RawXJC2Mojo.java
plugin-core/src/test/java/org/jvnet/jaxb2/maven2/RawXJC2MojoTest.java

Instead, the URIs of bindings are now created using the path of the
corresponding `JarEntry`. Thus, the `URLClassLoader` is no longer
required and does not pollute the JVM's ZIP cache.
Fixes #168.

Remove usage of unclosed URLClassLoader

---

README.md
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java

Fixing issue #285 by changing ref to new repo URL

JT-285 - previous ref to maven-jaxb2-plugin changed to jaxb-tools

---

maven-plugin/tests/jt-250/pom.xml
maven-plugin/tests/jt-250/src/main/java/org/example/testxjc/Main.java
maven-plugin/tests/jt-250/src/xsd/v1/purchaseorder.xsd
maven-plugin/tests/jt-250/src/xsd/v2/purchaseorder.xsd
maven-plugin/tests/pom.xml

Issue #250 as been fixed with latest release (2.0.2)
Just adding a new test project for NR Tests to not break it again

Adding new test project for issue 250 (fixed by 2.0.2)

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/IOUtils.java
maven-plugin/plugin-core/src/test/java/org/jvnet/jaxb/maven/util/IOUtilsTests.java

Phax does this PR which doesn't break build and fixes his issue #173 
Without it, he forked the project and maintains it (with jakarta support).

Fixing JT-173 (backport of modified version of PR made by phax)

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java
maven-plugin/plugin-core/src/test/java/org/jvnet/jaxb/maven/RawXJC2MojoTest.java
maven-plugin/tests/jt-194/pom.xml
maven-plugin/tests/jt-194/src/main/resources/purchaseorder.xjb
maven-plugin/tests/jt-194/src/main/resources/purchaseorder.xsd
maven-plugin/tests/pom.xml

This will exclude pom artifacts in collectBindingUrisFromDependencies and so, fix #194

Fixing issue JT-194 : adding TypeArtifactFilter to exclude pom artifacts

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/ClasspathCatalogResolver.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/LoggingCatalogResolver.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/MavenCatalogResolver.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/ReResolvingEntityResolverWrapper.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/ReResolvingInputSourceWrapper.java
maven-plugin/tests/MAVEN_JAXB2_PLUGIN-77/service/pom.xml
maven-plugin/tests/jt-244/pom.xml
maven-plugin/tests/jt-244/src/main/resources/bindings.xjb
maven-plugin/tests/jt-244/src/main/resources/catalog.xml
maven-plugin/tests/jt-244/src/main/resources/schemas/a.xsd
maven-plugin/tests/jt-244/src/main/resources/schemas/common/b.xsd
maven-plugin/tests/pom.xml

Mainly the goal here is to fix :
- https://github.com/highsource/jaxb-tools/issues/215 : reactivate the MAVEN_JAXB2_PLUGIN-77 with fix
- https://github.com/highsource/jaxb-tools/issues/244 : add a new test project (jt-244) that validate the fix
Also done some cosmetic changes to :
- maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/ClasspathCatalogResolver.java
- maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/MavenCatalogResolver.java

Fixing issues 215 / 244 due to xjc-ri changes from 2.3.4

---

jaxb-annotate-parent/samples/annotate/project-build.xml
jaxb-annotate-parent/tests/annotate/src/main/resources/schema.xsd
jaxb-annotate-parent/tests/annotate/src/test/java/org/jvnet/jaxb2_commons/tests/annotate/IssueJAP9TypeTest.java
jaxb-annox-parent/jaxb-annox/pom.xml
jaxb-annox-parent/jaxb-annox/src/main/java/org/jvnet/jaxb/annox/model/annotation/value/XStringAnnotationValue.java
jaxb-annox-parent/samples/po/project-build.xml
pom.xml

Fixes https://github.com/highsource/jaxb2-annotate-plugin/issues/9
Unescape escaped strings annox gets and that get quoted after by codemodel.

Fixing issue JAP-9

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/MavenCatalogResolver.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/ReResolvingEntityResolverWrapper.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/ReResolvingInputSourceWrapper.java
maven-plugin/tests/jt-306/common-model/pom.xml
maven-plugin/tests/jt-306/common-model/src/main/resources/META-INF/common.xjb
maven-plugin/tests/jt-306/common-model/src/main/resources/META-INF/common.xsd
maven-plugin/tests/jt-306/helper-ws-model/pom.xml
maven-plugin/tests/jt-306/helper-ws-model/src/main/resources/META-INF/helper-catalog.xml
maven-plugin/tests/jt-306/helper-ws-model/src/main/resources/META-INF/helper.xjb
maven-plugin/tests/jt-306/helper-ws-model/src/main/resources/META-INF/helper.xsd
maven-plugin/tests/jt-306/import-ws-model/pom.xml
maven-plugin/tests/jt-306/import-ws-model/src/main/resources/META-INF/import-catalog.xml
maven-plugin/tests/jt-306/import-ws-model/src/main/resources/META-INF/import.xjb
maven-plugin/tests/jt-306/import-ws-model/src/main/resources/META-INF/import.xsd
maven-plugin/tests/jt-306/pom.xml
maven-plugin/tests/pom.xml

Better handling of issue #244 which was partial fixed in previous PR and lead to #306 new issue.
Rollback of initial change in #244.
Only present resolved SystemId to DomForest if initial systemId does not exists.
Logs in overriden `getSystemId` in debug mode to indicate change in systemId presented if caller is `DOMForest` and if initial systemId points to a file which doesn't exisits.
Fix #306 and also still fix #244
Extra change :
`MavenCatalogResolver` : Changing log format (adding class name)

Fixing issue 306 : do some change in systemId handling for xjc 2.3.4+

---

README.md

Fixes #335 
Readme now points only to jaxb-tools repository and no external / deprecated website.

 Update README.md to point to jaxb-tools wiki links (issue 335)

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/IOUtils.java

This will try to close `URLClassLoader` created by XJCMojo when no more needed to free resources earlier in build.
Fixes #188

[#188] Classloaders not being closed for mojo classloader

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJC2Mojo.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/RelativeCatalog.java
maven-plugin/tests/gh-issue-19/pom.xml
maven-plugin/tests/pom.xml

Fixes #19 having a "RelativeCatalog" that adds automatically catalog entries for `REWRITE_SYSTEM` that starts with ".."

[#19] Fix relative Catalog Resolution

---

jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/defaultvalueplugin/DefaultValuePlugin.java
jaxb-plugins-parent/tests/defaultvalue/pom.xml
jaxb-plugins-parent/tests/defaultvalue/src/main/resources/Person.xsd

Fixes #395
This will generate defaultValue in field for attributes if specified by plugin's `all` option.

Issue 395 : add option to generate default-attribute-value in java class

---

README.md

Fixes #402 
Updating some sections of the readme with new link to migration guide and fixed some outdated sections of jaxb2 ref

[#402] update readme.md (with updated section of new namespaces)

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJCMojo.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJCMojo.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/XJCVersion.java
maven-plugin/plugin-core/src/test/java/org/jvnet/jaxb/maven/RawXJCMojoTest.java
maven-plugin/plugin/src/main/java/org/jvnet/jaxb/maven/XJCMojo.java

[#438] get version of XJC at runtime and dump it on source generation

---

README.md

Clarify the name difference between `jaxb2-basics` in versions 2.X and `jaxb-plugins` in versions 3.X and 4.X.
In issue #375, many codes were updated to change from `jaxb2-basics` to `jaxb-plugins`, but the docs are left out-of-date. I think at least the README should have a clarification for this change.
Here's the situation for new user like me:
- I read "JAXB Plugins (former JAXB Basics)" and thought "OK, so now it's called JAXB Plugins". But right below it there are subtitles called "Using JAXB Basics" and "JAXB Basics Plugins"... I was confused and thought "OK, It's name 'Basics' there is to distinguish from the main Maven plugin, huh!"
- Then throughout the docs, I only saw `jaxb2-basics` in the example codes, which lead me to search for "jaxb2-basics" on Maven Central. I only saw …

[#375] Update README.md

---

jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/simplify/SimplifyPlugin.java
jaxb-plugins-parent/tests/pom.xml
jaxb-plugins-parent/tests/simplify-01/src/test/java/org/jvnet/jaxb/plugin/simplify/tests01/Gh5Test.java
jaxb-plugins-parent/tests/simplify-03/pom.xml
jaxb-plugins-parent/tests/simplify-03/src/main/java/org/jvnet/jaxb/plugin/simplify/tests03/BaseElementRef.java
jaxb-plugins-parent/tests/simplify-03/src/main/java/org/jvnet/jaxb/plugin/simplify/tests03/DateAdapter.java
jaxb-plugins-parent/tests/simplify-03/src/main/resources/binding.xjb
jaxb-plugins-parent/tests/simplify-03/src/main/resources/schema.xsd
jaxb-plugins-parent/tests/simplify-03/src/test/java/org/jvnet/jaxb/plugin/simplify/tests03/Gh18Test.java
jaxb-plugins-parent/tests/simplify-03/src/test/java/org/jvnet/jaxb/plugin/simplify/tests03/Gh1Test.java
jaxb-plugins-parent/tests/simplify-03/src/test/java/org/jvnet/jaxb/plugin/simplify/tests03/Gh2Test.java
jaxb-plugins-parent/tests/simplify-03/src/test/java/org/jvnet/jaxb/plugin/simplify/tests03/Gh4Test.java
jaxb-plugins-parent/tests/simplify-03/src/test/java/org/jvnet/jaxb/plugin/simplify/tests03/Gh5Test.java
jaxb-plugins-parent/tests/simplify-03/src/test/java/org/jvnet/jaxb/plugin/simplify/tests03/Gh6Test.java
jaxb-plugins-parent/tests/simplify-03/src/test/java/org/jvnet/jaxb/plugin/simplify/tests03/RunSimplifyPlugin.java
jaxb-plugins-parent/tests/simplify-03/src/test/resources/org/jvnet/jaxb/plugin/simplify/tests03/simplifyElementsPropertyAsElementProperty.xml
jaxb-plugins-parent/tests/simplify-03/src/test/resources/org/jvnet/jaxb/plugin/simplify/tests03/simplifyReferencesPropertyAsElementProperty.xml
jaxb-plugins-parent/tests/simplify-03/src/test/resources/org/jvnet/jaxb/plugin/simplify/tests03/simplifyReferencesPropertyAsReferenceProperty.xml

Fixes #453
Fixes https://github.com/highsource/jaxb2-basics/issues/115
This PR will make simplifyPlugin respect globalBindings isSet / indexed properties

[#453] fixes for simplify plugin

---

README.md
hyperjaxb/ejb/tests/episodes/b/src/test/java/org/jvnet/hyperjaxb3/ejb/tests/episodes/b/tests/RunEpisodesBPlugin.java
hyperjaxb/maven/plugin/pom.xml
maven-plugin/plugin-core/pom.xml
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJCMojo.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJCMojo.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/ArtifactUtils.java
maven-plugin/plugin/pom.xml
maven-plugin/plugin/src/test/java/org/jvnet/jaxb/maven/JAXBGenerateTest.java
maven-plugin/testing/pom.xml
maven-plugin/testing/src/main/java/org/jvnet/jaxb/maven/test/RunXJCMojo.java
pom.xml

Fixes #334 
Fixes #459 
Move to maven-3 apis and set maven dependencies to high number to avoid CVE
Add new profile `check-maven-prerequisites` to check build against the minimal maven-version supported in `prerequisites` tags -> @mattrpav please upgrade github-workflow to add a build with this profile.
Will close #305 PR since upgrade done here.
No `maven-compat` module used here, so it's fully compatible with maven3 and drops support of maven2.
Doing this should make this plugin compatible with maven4

[#334] upgrade to maven-3 apis and set maven-minimal version to 3.1.0

---

pom.xml

Fixes #468 
Move to latest available version of maven-surefire and maven-failsafe plugins (3.2.3)

[#468] update maven surefire / failsafe plugins

---

jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/namespace_prefix/NamespacePrefixPlugin.java
jaxb-plugins-parent/tests/namespace/src/main/resources/binding.xjb
jaxb-plugins-parent/tests/namespace/src/main/resources/c.xsd
jaxb-plugins-parent/tests/namespace/src/test/java/org/jvnet/jaxb/tests/namespace/ATest.java
jaxb-plugins-parent/tests/namespace/src/test/java/org/jvnet/jaxb/tests/namespace/BTest.java
jaxb-plugins-parent/tests/namespace/src/test/java/org/jvnet/jaxb/tests/namespace/CTest.java
jaxb-plugins-parent/tests/namespace/src/test/java/org/jvnet/jaxb/tests/namespace/RunNamespacePlugin.java

Fixes #457 
Allow defining more than one prefix bindings with namespace-plugin
The plugin now reads the new `namespaceURI` attribute in binding configuration

[#457] add multiple namespaces prefix bindings

---

hyperjaxb/ejb/plugin/pom.xml
hyperjaxb/ejb/plugin/src/main/java/org/jvnet/jaxb/plugin/spring/AbstractSpringConfigurablePlugin.java
hyperjaxb/ejb/samples/customerservice-cxf/pom.xml
hyperjaxb/ejb/samples/customerservice-cxf/src/main/java/com/example/customerservice/service/CustomerServiceImpl.java
hyperjaxb/ejb/samples/pom.xml
jaxb-plugins-parent/jaxb-plugins-tools/pom.xml
pom.xml

Fixes #481
- Move spring dependency to hyperjaxb module only
- Upgrade spring to latest 5.x version (to keep jdk11 compatibility without breaking changes or dependencies on jakarta)

[#481] move spring dep to only hyperjaxb, upgrade spring

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java

Fixes #502 
Detect `EclipseEmptyBuildContext` used in eclipse m2e `runOnConfiguration` phase and do only setup phase of the plugin
Actual XJC run will then be done in the `runOnIncremental` phase after the setup phase

[#502] fix for m2e runOnConfiguration will only setupDirectories and no more execute actual XJC

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/JarScanner.java

Fixes #514 
Validate path of zipFile before taking it

[#514] Secure validation of path of zipFile

---

maven-plugin/plugin-core/src/test/java/org/jvnet/jaxb/maven/util/IOUtilsTests.java

Fixes #522 
Makes list of files in `IOUtilsTests.java` path depends on system build fileseparator.

[#522] test dependent platform on fileseparator

---

jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/EnumToStringStrategy.java
jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/tostring/ToStringPlugin.java
jaxb-plugins-parent/tests/enumtostring/pom.xml
jaxb-plugins-parent/tests/enumtostring/src/main/java/org/jvnet/jaxb/tests/enumtostring/MyEnumToStringStrategy.java
jaxb-plugins-parent/tests/enumtostring/src/main/resources/sample.xsd
jaxb-plugins-parent/tests/enumtostring/src/test/java/org/jvnet/jaxb/tests/enumtostring/ConsoleTest.java
jaxb-plugins-parent/tests/enumtostring/src/test/resources/log4j.properties
jaxb-plugins-parent/tests/pom.xml

Fixes #520 
Add extra parameter `toStringEnums` with following usage `-XtoString-toStringEnums=true` to generate `toString` methods on enums.
This will allow someone to override the output of enums in custom strategy.
See example in `enumtostring` project in tests

[#520] extends toStringPlugin to generate toString methods on enums

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/JarScanner.java

Fixes #514
Change `startsWith("..")` and `startsWith("/")` to true path validation (make sure the file is written in same directory as expected

[#514] fix contains('..') in path in jar file

---

jaxb-plugins-parent/jaxb-plugins-runtime/pom.xml

Fixes #533 
Adds the following entry in `MANIFEST.MF` of jaxb-plugins-runtime artifact :
> `Automatic-Module-Name: org.jvnet.jaxb.plugins.runtime`

[#533] add Automatic-Module-Name in jaxb-plugins-runtime

---

pom.xml

Fixes #548 
Upgrading `maven-bundle-plugin`
This will fix `MANIFEST.MF` generation from
```
Require-Capability: osgi.ee;filter:="(osgi.ee=UNKNOWN)"
```
to
```
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=11))"
```

[#548] upgrade maven-bundle-plugin

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJCMojo.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJCMojo.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/ArtifactUtils.java

Fixes #560 
This make `xercesImpl` and `xml-apis` doesnt come into final classpath of maven-plugin since they could conflict with other classes and fail generation

[#560] add configuration for artifact exclusions in final classpath (which default to exclude xercesImpl and xml-apis artifacts)

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJCMojo.java
maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/ArtifactUtils.java

Fixes #582 
Add extra details if resolution failed at some point instead of failing later with NPE

[#582] enhance resolution artifact process if not success

---

jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/defaultvalueplugin/DefaultValuePlugin.java
jaxb-plugins-parent/tests/defaultvalue/src/main/resources/Person.xsd
jaxb-plugins-parent/tests/defaultvalue/src/test/java/org/jvnet/jaxb2_commons/tests/defaultvalue/MathTypesTest.java

Fixes #592 
Add `BigInteger` and `BigDecimal` to supported types for default-value-plugin

[#592] handle BigInteger / BigDecimal in default-value-plugin

---

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJC2Mojo.java

Fixes #598 
Based on detection of `JAXBContextFactory` class which is only present in JAXB 2.3 before triggerring 2.2 / 2.1 and 2.0 class / methods detection

[#598] fix JAXB API 2.2 detected if 2.3 is taken

---

hyperjaxb/ejb/roundtrip/src/main/java/org/jvnet/hyperjaxb3/ejb/test/AbstractEntityManagerSamplesTest.java
hyperjaxb/ejb/samples/po-customized-eclipselink/project-build.xml
hyperjaxb/ejb/samples/po-initial/project-build.xml
hyperjaxb/ejb/samples/uniprot/project-build.xml
hyperjaxb/ejb/schemas/customizations/pom.xml
hyperjaxb/ejb/schemas/customizations/src/test/java/org/jvnet/hyperjaxb3/ejb/schemas/customizations/tests/UnmarshalPersistenceTest.java
hyperjaxb/ejb/templates/basic/project-build.xml
jaxb-annox-parent/jaxb-annox/pom.xml
jaxb-annox-parent/jaxb-annox/src/test/java/org/jvnet/jaxb/annox/parser/tests/XAnnotationParserAnnotationExprTest.java
jaxb-annox-parent/samples/po/project-build.xml
jaxb-plugins-parent/jaxb-plugins-testing/pom.xml
jaxb-plugins-parent/jaxb-plugins-testing/src/main/java/org/jvnet/jaxb/test/AbstractSamplesTest.java
jaxb-plugins-parent/samples/basic/project-build.xml
jaxb-plugins-parent/samples/po-simple/project-build.xml
jaxb-plugins-parent/samples/po/project-build.xml
pom.xml

Fixes #589 
Remove `commons-io` dependency

[#589] remove commons-io usage in all places

---

hyperjaxb/ejb/runtime/src/main/java/org/jvnet/hyperjaxb3/xml/bind/annotation/adapters/XMLGregorianCalendarAsDateTime.java
hyperjaxb/ejb/runtime/src/main/java/org/jvnet/hyperjaxb3/xml/bind/annotation/adapters/XMLGregorianCalendarAsTime.java
hyperjaxb/ejb/runtime/src/test/java/org/jvnet/hyperjaxb3/xml/bind/annotation/adapters/XMLGregorianCalendarAsDateTimeTest.java
hyperjaxb/ejb/runtime/src/test/java/org/jvnet/hyperjaxb3/xml/bind/annotation/adapters/XMLGregorianCalendarAsTimeTest.java

Fixes #600 
If date is in the past (of epoch), getMillis return negative value, which ends in error

[#600] fix Time to Calendar conversion if in the past

---

jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/propertylistenerinjector/PropertyListenerInjectorPlugin.java
jaxb-plugins-parent/tests/propertylistenerinjector/src/test/java/org/jvnet/jaxb/tests/propertylistenerinjector/AddressTest.java

Fixes #616 
Update of #617 
Fixes not impacting setter methods in plugin's code
Updated test case

[#616] fix PropertyListenerInjectorPlugin setters not updated
