plugin-core/src/main/resources/org/jvnet/jaxb2/maven2/addIfExistsToEpisodeSchemaBindings.xslt
Fix ```addIfExistsToEpisodeSchemaBindings.xslt``` according to highsource/maven-jaxb2-plugin#61
=> Fix if-exists for all bindings in episode file

.github/workflows/maven-build-action.yaml
(cherry picked from commit cc3faadb5d6214baaf5a6e09cb80ff5c0c57486c)
=> [#267] Add GH action for 0.15.x bracnh

maven-plugin/plugin/pom.xml, maven-plugin/testing/pom.xml
Make maven dependencies as provided to fix #275
=> Fixing JT-275 : makes maven artifact as provided scopes

maven-plugin/plugin-core/pom.xml, pom.xml
See : https://github.com/highsource/jaxb-tools/issues/176
=> JT-176 : Bump plexus-utils / plexus-build-api

maven-plugin/tests/jt-250/pom.xml
Fixup of #250 and #289 (`-P all` does not compile anymore)
=> fixup of pom with good jaxb2-basics artifact

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJC2Mojo.java, maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java, maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/ReResolvingEntityResolverWrapper.java, maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/ReResolvingInputSourceWrapper.java, maven-plugin/tests/issues/pom.xml
Fixes #336 : adding new parameter to disable fix introduced in 2.0.5 release due to #329 #306
=> [#336] adding new parameter to disable fix introduced in 2.0.5

README.md, hyperjaxb/ejb/plugin/src/main/java/org/jvnet/hyperjaxb3/ejb/strategy/customizing/Customizing.java, hyperjaxb/ejb/plugin/src/main/java/org/jvnet/hyperjaxb3/ejb/strategy/model/CreatePropertyInfos.java, hyperjaxb/ejb/schemas/persistence/pom.xml, hyperjaxb/maven/plugin/src/main/java/org/jvnet/hyperjaxb3/maven2/Hyperjaxb3Mojo.java, pom.xml
Fixing mvn javadoc build for hyperjaxb3
=> fix javadoc

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java
Fixes #100 : now m2eclipse can generate do generate goal of `jaxb-maven-plugin` when `scanDependenciesForBindings` is set to `true`
Reproduced with latest release (2.0.5)
No problem with 2.0.7-SNAPSHOT builded with this fix :
=> [#100] Fixing eclipse errors reading directory as project resource

.github/workflows/maven-build-action.yaml
- remove -fn
- add release dry run operations
=> [#346] Update maven build actions

.github/workflows/maven-build-action.yaml, jaxb-tools-docs/pom.xml, pom.xml
- Disable gh-19
- Convert jaxb-annox to proper bundle (don't leave edited file on disk for release)
- Disable gpg signing for CI testing
- Add dummy gpg key
- Maven plugin updates
=> [#346] Comment out GH #19 test as it fails on GH Action

hyperjaxb/ejb/samples/po-customized-toplink/project-build.xml, hyperjaxb/ejb/samples/po-initial/project-build.xml, hyperjaxb/ejb/samples/pom.xml, hyperjaxb/ejb/samples/uniprot/project-build.xml, hyperjaxb/ejb/templates/basic/project-build.xml, maven-plugin/plugin-core/pom.xml, maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java, maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/ClasspathCatalogResolver.java, maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/MavenCatalogResolver.java, maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/RelativeCatalog.java, maven-plugin/plugin-core/src/test/java/org/jvnet/jaxb/maven/resolver/tools/tests/MavenCatalogResolverTest.java, maven-plugin/tests/gh-issue-19/b/pom.xml, maven-plugin/tests/gh-issue-19/b/src/main/resources/b/b.cat, maven-plugin/tests/gh-issue-19/pom.xml, maven-plugin/tests/pom.xml
Fixes #366 
Fixes #19 for jdk8 build too
=> GH-366 : re-enable gh-issue-19 project

jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/ComposedIgnoring.java
=> [#415] fix warn with list of qnames

README.md
Fixes #427 
Update readme to point to v4 ref of JAXB API / RI and support of older versions ref
=> [#427] Update readme for v4

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJCMojo.java
Fixes #429 
To be backported in 3.X
=> [#429] Fixing error warning on javax classes not found

jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/codegenerator/FloatCodeGenerator.java
=> [#435] fix FloatCodeGenerator calling wrong method

jaxb-tools-docs/pom.xml, jaxb-tools-docs/src/main/docs/jaxb-tools-docs/jaxb-tools-user-guide-content.adoc
=> [#439] fix asciidoctor maven-plugin config

jaxb-annotate-parent/tests/pom.xml, maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJCMojo.java, maven-plugin/tests/javadoc/pom.xml, maven-plugin/tests/javadoc/src/main/resources/schema.xsd, maven-plugin/tests/javadoc/src/test/resources/log4j.properties, maven-plugin/tests/pom.xml, pom.xml
Fixes #425 
Upgrade to jaxb-ri 4.0.4
=> [#425] upgrade to jaxb-ri 4.0.4 (add test project for javadoc)

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJCMojo.java, maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJCMojo.java, maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/ReResolvingEntityResolverWrapper.java
Fixes #338 
Let the fix auto-enabled if runtime le 4.0.4
=> [#338] enable reresolution work around based on jaxb-ri used

README.md
Update readme to mention xml annotation removal
=> Update README.md (mention remove xml annotation). Need to update wiki

hyperjaxb/pom.xml
Fixes #490 
Remove unused dependency
=> [#490] remove net.sourceforge.collections:collections-generic dep

hyperjaxb/ejb/templates/pom.xml, maven-plugin/tests/pom.xml, maven-plugin/tests/res-resources/pom.xml, maven-plugin/tests/res-resources/src/main/resources/bindings.xjb, maven-plugin/tests/res-resources/src/main/resources/catalog.cat, maven-plugin/tests/res-resources/src/main/resources/schemas/purchaseorder.xsd, maven-plugin/tests/res-resources/src/main/resources/schemas/schema-other.xsd, maven-plugin/tests/res-resources/src/main/resources/schemas/schema.xs, maven-plugin/tests/res-resources/src/main/resources/schemas/schema.xsd, maven-plugin/tests/res-star/pom.xml
Fixes #486 
Make parallel build OK again (with `-T1C`)
=> [#486] fix parallel build

jaxb-plugins-parent/tests/fluentapi/pom.xml, jaxb-plugins-parent/tests/fluentapi/src/main/resources/Example.xsd, jaxb-plugins-parent/tests/fluentapi/src/test/java/org/jvnet/jaxb/tests/fluentapi/BaseTest.java, jaxb-plugins-parent/tests/fluentapi/src/test/java/org/jvnet/jaxb/tests/fluentapi/PrimitivesAndUnboxedPrimitivesTest.java, jaxb-plugins-parent/tests/fluentapi/src/test/resources/log4j.properties, jaxb-plugins-parent/tests/pom.xml
Add test case for fluent-api XJC plugin
=> [#508] add test project for fluent-api plugin

pom.xml
Fixes #527
Fixes #526 by transitivity upgrade
=> [#527][#526] upgrade to jaxb-ri 4.0.5

pom.xml
Fixes #482 
Still working with minimal maven version supported (3.1.0)
=> [#482] upgrade maven-core version to latest to fix guava dependency

jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/fluent_api/FluentMethodType.java
Fixes https://github.com/highsource/jaxb2-annotate-plugin/issues/57
=> [#JAP-57] : add javadoc from with-method from fluent-api plugin

maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/JarScanner.java
=> [#514] third try to fix security alert

README.md
=> [#546] fix README.md javax -> jakarta

README.md
Fixes #229 
Add table to `Readme.MD` in order to understand compatibility chart in main branch
=> [#229] add project version compatibility chart

pom.xml
Fixes #591 
Update commons-io lib to latest 2.19.0
=> [#591] update to commons-io 2.19.0

jaxb-annotate-parent/samples/annotate/project-build.xml, jaxb-annox-parent/samples/po/project-build.xml, jaxb-plugins-parent/samples/cxf/pom.xml, pom.xml
Fixes #609 
Remove `commons-text` dependency (and wrong dependency on `cxf-codegen-plugin` which has transitive dep on `commons-text`)
=> [#609] remove commons-text dependency

.github/workflows/maven-build-action.yaml
Fixes #603 
Add jdk25 early adopter to build matrix
=> [#603] add jdk25 EA in java build version

Jenkinsfile
Fixes #645 
update release dry run Jenkinsfile profiles :
- remove all
- add sonatype-oss-release,release
- keep release-dry-run
=> [#645] update release dry run Jenkinsfile profiles
